# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hotline < Formula
  desc "A client-side workflow engine/executor for AI applications."
  homepage "https://github.com/leslieleung/hotline"
  version "0.0.1"

  on_macos do
    on_intel do
      url "https://github.com/LeslieLeung/hotline/releases/download/v0.0.1/hotline_0.0.1_darwin_amd64.tar.gz"
      sha256 "0a183c1cd1d14ddf62425bc8095e81944effe6e3ec9b31d15a3b69f4f70cd1d8"

      def install
        bin.install "hotline"
      end
    end
    on_arm do
      url "https://github.com/LeslieLeung/hotline/releases/download/v0.0.1/hotline_0.0.1_darwin_arm64.tar.gz"
      sha256 "c603b7f0e8d6d775642be0f76720d68acdeb9584981c659a57c549c74cf98a02"

      def install
        bin.install "hotline"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/LeslieLeung/hotline/releases/download/v0.0.1/hotline_0.0.1_linux_amd64.tar.gz"
        sha256 "5366b1e4107f4373babe74d7b7313340499c7737fea18f423f63458a42c22333"

        def install
          bin.install "hotline"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/LeslieLeung/hotline/releases/download/v0.0.1/hotline_0.0.1_linux_arm64.tar.gz"
        sha256 "12b53a2c320cbd3b6dc6112fedc4e7435658222ec5797737f7b5d137823b953a"

        def install
          bin.install "hotline"
        end
      end
    end
  end
end
