# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hotline < Formula
  desc "A client-side workflow engine/executor for AI applications."
  homepage "https://github.com/leslieleung/hotline"
  version "0.1.0"

  on_macos do
    on_intel do
      url "https://github.com/LeslieLeung/hotline/releases/download/v0.1.0/hotline_0.1.0_darwin_amd64.tar.gz"
      sha256 "9fb02e097b66fac00759ce4d9ec2fd22d4f7dd82639de94e9c0467fa6eb235f9"

      def install
        bin.install "hotline"
      end
    end
    on_arm do
      url "https://github.com/LeslieLeung/hotline/releases/download/v0.1.0/hotline_0.1.0_darwin_arm64.tar.gz"
      sha256 "1a2b3fd056005f0cc095d16fb0b2e963fc4c7a73f490284899291a8ad7bc354e"

      def install
        bin.install "hotline"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/LeslieLeung/hotline/releases/download/v0.1.0/hotline_0.1.0_linux_amd64.tar.gz"
        sha256 "470cb3cec3aa1c4d4e1d9f6ab72c62e73bfd5bd2a35fbb5bdd85636968c0773c"

        def install
          bin.install "hotline"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/LeslieLeung/hotline/releases/download/v0.1.0/hotline_0.1.0_linux_arm64.tar.gz"
        sha256 "778106cbc185ad6cd4dddfe28345603a73cd740d03dc8b4b105d942e0a74ee3f"

        def install
          bin.install "hotline"
        end
      end
    end
  end
end
